---
- name: install apache & php & mysql
  hosts: test-servers
  become: true
  gather_facts: true
  tasks:
  - name: "Install apache2"
    package: name=httpd state=present
  - name: "Install apache2-php5"
    package: name=php state=present
    package: name=php-opcache state=present
  - name: "Install mysqlserver"
    package: name=mysql-server state=present

