---
- hosts: test-servers
  vars:
    http_port: 80
    max_clients: 200
  become: yes 
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
